[build]
  base = "client"
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  REACT_APP_API_BASE_URL = "https://sajufortune-api.onrender.com/api"

[git]
  submodules = false